-- Email Templates table
-- Run this in your Supabase SQL Editor

create table if not exists email_templates (
  id uuid default uuid_generate_v4() primary key,
  name varchar(255) not null,
  slug varchar(255) unique not null,
  description text,
  category varchar(100) not null default 'transactional',
  subject_template text,
  html_body text not null,
  trigger_event varchar(100),
  is_active boolean default true not null,
  variables jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_email_templates_slug on email_templates(slug);
create index if not exists idx_email_templates_category on email_templates(category);
create index if not exists idx_email_templates_trigger on email_templates(trigger_event);

-- Seed: All existing email templates from src/lib/email.ts

insert into email_templates (name, slug, description, category, subject_template, html_body, trigger_event, variables) values

-- Auth emails
('Email Verification', 'email-verification', '6-digit OTP code for email verification', 'transactional',
 'Your verification code: {{code}}',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#a855f7,#06b6d4);margin:0 auto 16px;line-height:48px;text-align:center;"><span style="color:white;font-size:20px;font-weight:700;">&#9993;</span></div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">Verify your email</h1></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">Hi {{name}},</p><p style="margin:12px 0 0;font-size:15px;color:#e0e0e0;line-height:1.6;">Use the code below to verify your email address:</p></td></tr><tr><td style="padding:0 32px 24px;text-align:center;"><div style="display:inline-block;background:rgba(168,85,247,0.1);border:1px solid rgba(168,85,247,0.2);border-radius:12px;padding:20px 40px;"><span style="font-size:32px;font-weight:800;color:#a78bfa;letter-spacing:8px;">{{code}}</span></div></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:13px;color:#94a3b8;line-height:1.5;">This code expires in 15 minutes. If you didn''t create an account, you can safely ignore this email.</p></td></tr></table></td></tr></table></div>',
 'auth.verification', '["code","name","email"]'::jsonb),

('Password Reset', 'password-reset', 'Password reset link with 1hr expiry', 'transactional',
 'Reset your {{platform_name}} password',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#f59e0b,#ef4444);margin:0 auto 16px;line-height:48px;text-align:center;"><span style="color:white;font-size:20px;font-weight:700;">&#128274;</span></div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">Reset your password</h1></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">Hi {{name}},</p><p style="margin:12px 0 0;font-size:15px;color:#e0e0e0;line-height:1.6;">We received a request to reset your password. Click the button below to set a new one:</p></td></tr><tr><td style="padding:0 32px 24px;text-align:center;"><a href="{{reset_url}}" style="display:inline-block;padding:14px 36px;background:linear-gradient(135deg,#f59e0b,#ef4444);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">Reset Password</a></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:13px;color:#94a3b8;line-height:1.5;">This link expires in 1 hour. If you didn''t request a password reset, you can safely ignore this email.</p></td></tr></table></td></tr></table></div>',
 'auth.password_reset', '["token","name","email"]'::jsonb),

('Welcome Email', 'welcome-email', 'Post-verification welcome with Create Store CTA', 'transactional',
 'Welcome to {{platform_name}}!',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#a855f7,#06b6d4);margin:0 auto 16px;line-height:48px;text-align:center;"><span style="color:white;font-size:20px;">&#10024;</span></div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">Welcome to {{platform_name}}!</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">Your email has been verified</p></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">Hi {{name}},</p><p style="margin:12px 0 0;font-size:15px;color:#e0e0e0;line-height:1.6;">Your account is ready. Create your store, add products, and start selling on WhatsApp in minutes.</p></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/onboarding" style="display:inline-block;padding:12px 32px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">Create Your Store</a></td></tr></table></td></tr></table></div>',
 'auth.welcome', '["name","email"]'::jsonb),

-- Subscription emails
('Trial Expiry Reminder', 'trial-expiry-reminder', 'Urgency-coded reminder when trial expires', 'subscription',
 'Your {{platform_name}} trial expires in {{days_left}} days — {{store_name}}',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="font-size:40px;margin-bottom:12px;">&#9203;</div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">Trial Expiring {{urgency}}</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">{{store_name}}</p></td></tr><tr><td style="padding:0 32px 24px;"><div style="background:rgba(234,179,8,0.08);border:1px solid rgba(234,179,8,0.15);border-radius:12px;padding:20px;text-align:center;"><p style="margin:0;font-size:32px;font-weight:700;color:#eab308;">{{days_left}}</p><p style="margin:4px 0 0;font-size:13px;color:#94a3b8;">days remaining</p></div></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">Your free trial for <strong>{{store_name}}</strong> expires {{urgency}}. Upgrade now to keep your store live and your products visible to customers.</p></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/upgrade" style="display:inline-block;padding:14px 36px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">Upgrade Now</a></td></tr></table></td></tr></table></div>',
 'subscription.trial_expiry', '["store_name","store_slug","days_left"]'::jsonb),

('Subscription Expiry Reminder', 'subscription-expiry-reminder', 'Plan-aware subscription expiry reminder', 'subscription',
 'Your {{platform_name}} subscription expires in {{days_left}} days — {{store_name}}',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="font-size:40px;margin-bottom:12px;">&#9203;</div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">Subscription Expiring {{urgency}}</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">{{store_name}}</p></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">Your <strong>{{plan}}</strong> subscription for <strong>{{store_name}}</strong> expires {{urgency}}. Renew now to keep your store live with all your plan features.</p></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/upgrade" style="display:inline-block;padding:14px 36px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">Renew Now</a></td></tr></table></td></tr></table></div>',
 'subscription.expiry', '["store_name","plan","days_left"]'::jsonb),

-- Inventory emails
('Low Stock Alert', 'low-stock-alert', 'Alert when product stock falls below threshold', 'inventory',
 'Low stock alert — {{store_name}}',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#eab308,#f97316);margin:0 auto 16px;line-height:48px;text-align:center;"><span style="color:white;font-size:20px;">&#9888;</span></div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">Low Stock Alert</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">{{store_name}}</p></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">{{items_list}}</p></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/dashboard/products" style="display:inline-block;padding:12px 32px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">Manage Products</a></td></tr></table></td></tr></table></div>',
 'inventory.low_stock', '["store_name","store_slug","items_list","threshold"]'::jsonb),

-- Order emails
('New Order Notification', 'new-order-notification', 'Notify vendor of new WhatsApp order', 'order',
 'New order #{{order_id}} from {{customer_name}} - {{store_name}}',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#a855f7,#06b6d4);margin:0 auto 16px;line-height:48px;text-align:center;"><span style="color:white;font-size:20px;">&#128722;</span></div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">New Order Received</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">{{store_name}}</p></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">Order #{{order_id}} from {{customer_name}}</p></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/dashboard" style="display:inline-block;padding:12px 32px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">View in Dashboard</a></td></tr></table></td></tr></table></div>',
 'order.new', '["store_name","order_id","customer_name","customer_phone","items","total","notes"]'::jsonb),

('Order Status Update', 'order-status-update', 'Notify customer of order status change', 'order',
 'Order #{{order_id}} {{status}} - {{store_name}}',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="font-size:40px;margin-bottom:12px;">&#127881;</div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">Order {{status}}</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">{{store_name}}</p></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">Your order #{{order_id}} has been {{status}}.</p></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/order/{{order_id}}" style="display:inline-block;padding:12px 32px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">View Order</a></td></tr></table></td></tr></table></div>',
 'order.status_update', '["store_name","order_id","status","items","total"]'::jsonb),

-- Support emails
('New Support Ticket', 'new-support-ticket', 'Alert admin of new vendor support ticket', 'support',
 'New support ticket #{{ticket_id}}: {{subject}}',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#a855f7,#06b6d4);margin:0 auto 16px;line-height:48px;text-align:center;"><span style="color:white;font-size:20px;">&#128172;</span></div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">New Support Ticket</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">Ticket #{{ticket_id}}</p></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">A vendor has submitted a new support ticket. Log in to the admin panel to view and respond.</p></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/admin/support" style="display:inline-block;padding:12px 32px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">View Ticket</a></td></tr></table></td></tr></table></div>',
 'support.new_ticket', '["ticket_id","subject","category"]'::jsonb),

('Support Reply Notification', 'support-reply-notification', 'Notify vendor when admin replies to ticket', 'support',
 'Support reply on ticket #{{ticket_id}}: {{subject}}',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#10b981,#06b6d4);margin:0 auto 16px;line-height:48px;text-align:center;"><span style="color:white;font-size:20px;">&#128172;</span></div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">Support Reply</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">Ticket #{{ticket_id}}</p></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">The support team has replied to your ticket <strong>"{{subject}}"</strong>:</p></td></tr><tr><td style="padding:0 32px 24px;"><div style="padding:14px 18px;background:rgba(16,185,129,0.06);border-left:3px solid #10b981;border-radius:0 8px 8px 0;"><p style="margin:0;font-size:13px;color:#e0e0e0;line-height:1.5;">{{reply_preview}}</p></div></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/dashboard/support?ticket={{ticket_id}}" style="display:inline-block;padding:12px 32px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">View Ticket</a></td></tr></table></td></tr></table></div>',
 'support.reply', '["ticket_id","subject","reply_preview"]'::jsonb),

-- Marketing emails
('Trial Nurture Day 1', 'trial-nurture-day1', 'Welcome aboard — 3 steps to first order', 'marketing',
 'Your store is live! 3 steps to get your first order',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#a855f7,#06b6d4);margin:0 auto 16px;line-height:48px;text-align:center;"><span style="color:white;font-size:20px;">&#127881;</span></div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">Welcome aboard!</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">Your store is live</p></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">Hi {{name}},</p><p style="margin:12px 0 0;font-size:15px;color:#e0e0e0;line-height:1.6;">Your store <strong>{{store_name}}</strong> is now live! Here are 3 things to do right now to get your first order:</p></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/{{store_slug}}" style="display:inline-block;padding:12px 32px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">View Your Store</a></td></tr></table></td></tr></table></div>',
 'marketing.trial_nurture_day1', '["name","store_name","store_slug"]'::jsonb),

('Trial Nurture Day 3', 'trial-nurture-day3', 'Pro tip — add products, share link', 'marketing',
 'Add your first product to {{store_name}} — it takes 2 minutes',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#10b981,#06b6d4);margin:0 auto 16px;line-height:48px;text-align:center;"><span style="color:white;font-size:20px;">&#128161;</span></div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">Add your first product</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">{{store_name}}</p></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">Hi {{name}},</p><p style="margin:12px 0 0;font-size:15px;color:#e0e0e0;line-height:1.6;">You haven''t added any products yet. It takes 2 minutes to add your first product.</p></td></tr><tr><td style="padding:0 32px 24px;"><div style="padding:16px 20px;background:rgba(16,185,129,0.06);border-left:3px solid #10b981;border-radius:0 8px 8px 0;"><p style="margin:0;font-size:14px;color:#e0e0e0;line-height:1.5;"><strong style="color:#10b981;">Pro tip:</strong> Vendors who add at least 5 products and share their link within the first 3 days get 70% more orders in their first week.</p></div></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/dashboard" style="display:inline-block;padding:12px 32px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">Add Products Now</a></td></tr></table></td></tr></table></div>',
 'marketing.trial_nurture_day3', '["name","store_name","store_slug","product_count"]'::jsonb),

('Trial Nurture Day 5', 'trial-nurture-day5', 'Trial expiring — upgrade CTA', 'marketing',
 'Your trial expires in {{days_left}} days — upgrade to keep {{store_name}} live',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#f59e0b,#ef4444);margin:0 auto 16px;line-height:48px;text-align:center;"><span style="color:white;font-size:20px;">&#9888;</span></div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">Your trial expires in {{days_left}} days</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">Keep your store live</p></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">Hi {{name}},</p><p style="margin:12px 0 0;font-size:15px;color:#e0e0e0;line-height:1.6;">Your free trial for <strong>{{store_name}}</strong> expires in {{days_left}} day{{days_left}}. Upgrade now to keep your store live and continue receiving orders.</p></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/upgrade" style="display:inline-block;padding:14px 36px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">Upgrade Now</a></td></tr></table></td></tr></table></div>',
 'marketing.trial_nurture_day5', '["name","store_name","store_slug","days_left"]'::jsonb),

('Upgrade Thank You', 'upgrade-thank-you', 'Post-upgrade confirmation', 'marketing',
 'Welcome to {{plan}} — {{store_name}} is now premium',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#10b981,#06b6d4);margin:0 auto 16px;line-height:48px;text-align:center;"><span style="color:white;font-size:20px;">&#127881;</span></div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">Welcome to {{plan}}!</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">Thank you for upgrading</p></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">Hi {{name}},</p><p style="margin:12px 0 0;font-size:15px;color:#e0e0e0;line-height:1.6;">You''ve upgraded <strong>{{store_name}}</strong> to the <strong>{{plan}}</strong> plan. Your store now has all premium features unlocked.</p></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/dashboard" style="display:inline-block;padding:12px 32px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">Go to Dashboard</a></td></tr></table></td></tr></table></div>',
 'marketing.upgrade', '["name","store_name","plan"]'::jsonb),

('Win-Back Email', 'win-back-email', 'Re-engagement for expired subscriptions', 'marketing',
 'We miss you — bring {{store_name}} back online',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#a855f7,#06b6d4);margin:0 auto 16px;line-height:48px;text-align:center;"><span style="color:white;font-size:20px;">&#128148;</span></div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">We miss you!</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">{{store_name}} is offline</p></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">Hi {{name}},</p><p style="margin:12px 0 0;font-size:15px;color:#e0e0e0;line-height:1.6;">It''s been {{days_since_expiry}} days since your subscription expired. Your store <strong>{{store_name}}</strong> is currently offline and customers can''t browse your products.</p></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/upgrade" style="display:inline-block;padding:14px 36px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">Reactivate Your Store</a></td></tr></table></td></tr></table></div>',
 'marketing.win_back', '["name","store_name","store_slug","days_since_expiry"]'::jsonb),

('Weekly Digest', 'weekly-digest', 'Weekly stats report for active vendors', 'marketing',
 'Weekly report for {{store_name}} — {{visits}} visits, {{orders}} orders',
 '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#06060b;padding:40px 20px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#13131d;border:1px solid rgba(255,255,255,0.06);border-radius:16px;overflow:hidden;"><tr><td style="padding:32px 32px 24px;text-align:center;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#a855f7,#06b6d4);margin:0 auto 16px;line-height:48px;text-align:center;"><span style="color:white;font-size:20px;">&#128200;</span></div><h1 style="margin:0;font-size:22px;font-weight:700;color:#f1f5f9;">Your Weekly Report</h1><p style="margin:6px 0 0;font-size:14px;color:#94a3b8;">{{store_name}}</p></td></tr><tr><td style="padding:0 32px 24px;"><p style="margin:0;font-size:15px;color:#e0e0e0;line-height:1.6;">Hi {{name}},</p><p style="margin:12px 0 0;font-size:15px;color:#e0e0e0;line-height:1.6;">Here''s your weekly performance summary.</p></td></tr><tr><td style="padding:8px 32px 32px;text-align:center;"><a href="{{app_url}}/dashboard" style="display:inline-block;padding:12px 32px;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;font-size:14px;font-weight:600;border-radius:10px;text-decoration:none;">View Full Dashboard</a></td></tr></table></td></tr></table></div>',
 'marketing.weekly_digest', '["name","store_name","store_slug","visits","orders","whatsapp_clicks","top_product"]'::jsonb)

on conflict (slug) do nothing;
